version: '3'
services:
  frontend:
    image: edna-web
    container_name: edna-web
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    network_mode: bridge
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
