version: "3.7"
services:
  pg-eDNA:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  redis-eDNA:
    image: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - data:/var/lib/redis/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - pg-eDNA
      - redis-eDNA
    networks:
      - default
    ports:
      - "8080:8080"
  reverse-proxy:
    build: ./nginx
    tty: true
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  data:
